repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ['--remove']

  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
  - repo: git@github.com:humitos/mirrors-docformatter.git
    rev: v1.0
    hooks:
      - id: docformatter
        args: ['--in-place', '--pre-summary-newline']
