language: python

python:
  - 3.6

install:
  - pip install pipenv
  - pipenv install --dev --three


script:
  - pipenv run pre-commit run --all-files
  - pipenv run pytest --cov=./

after_success:
  - pipenv run codecov
